def sum_as_string(a: int, b: int) -> str: ...

def say_hello(name: str) -> str: ...

def say_more_hello(name: str, conf: str = "blah") -> str: ...

def check_reg(filename: str, name: str) -> str: ...
